//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdleMaster.localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdleMaster.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;About ähnelt.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Accept ähnelt.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Add ähnelt.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Game to Blacklist ähnelt.
        /// </summary>
        internal static string add_game_blacklist {
            get {
                return ResourceManager.GetString("add_game_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display advanced authentication information ähnelt.
        /// </summary>
        internal static string advanced_auth {
            get {
                return ResourceManager.GetString("advanced_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle Master Authentication Data ähnelt.
        /// </summary>
        internal static string auth_data {
            get {
                return ResourceManager.GetString("auth_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Badge page didn&apos;t load, will retry in __num__ seconds ähnelt.
        /// </summary>
        internal static string badge_didnt_load {
            get {
                return ResourceManager.GetString("badge_didnt_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Blacklist ähnelt.
        /// </summary>
        internal static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Blacklist Current Game ähnelt.
        /// </summary>
        internal static string blacklist_current_game {
            get {
                return ResourceManager.GetString("blacklist_current_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die card drops remaining ähnelt.
        /// </summary>
        internal static string card_drops_remaining {
            get {
                return ResourceManager.GetString("card_drops_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display information above
        ///
        ///[WARNING]
        ///Do not share this information with anyone,
        ///as it could potentially be used by an attacker to log into
        ///your Steam account. ähnelt.
        /// </summary>
        internal static string cookie_warning {
            get {
                return ResourceManager.GetString("cookie_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently in-game ähnelt.
        /// </summary>
        internal static string currently_ingame {
            get {
                return ResourceManager.GetString("currently_ingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E&amp;xit ähnelt.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;File ähnelt.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Game ähnelt.
        /// </summary>
        internal static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die games left to idle ähnelt.
        /// </summary>
        internal static string games_left_to_idle {
            get {
                return ResourceManager.GetString("games_left_to_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Help ähnelt.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hrs on record ähnelt.
        /// </summary>
        internal static string hrs_on_record {
            get {
                return ResourceManager.GetString("hrs_on_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle each game individually ähnelt.
        /// </summary>
        internal static string idle_individual {
            get {
                return ResourceManager.GetString("idle_individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle Master is connected to Steam ähnelt.
        /// </summary>
        internal static string idle_master_connected {
            get {
                return ResourceManager.GetString("idle_master_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle Master is not connected to Steam ähnelt.
        /// </summary>
        internal static string idle_master_notconnected {
            get {
                return ResourceManager.GetString("idle_master_notconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle Master Settings ähnelt.
        /// </summary>
        internal static string idle_master_settings {
            get {
                return ResourceManager.GetString("idle_master_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die idle now ähnelt.
        /// </summary>
        internal static string idle_now {
            get {
                return ResourceManager.GetString("idle_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle games with more than 2 hours individually, then simultaneously ähnelt.
        /// </summary>
        internal static string idle_onethenmany {
            get {
                return ResourceManager.GetString("idle_onethenmany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle games simultaneously up to 2 hours, then individually ähnelt.
        /// </summary>
        internal static string idle_simultaneous {
            get {
                return ResourceManager.GetString("idle_simultaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idling Behavior ähnelt.
        /// </summary>
        internal static string idling_behavior {
            get {
                return ResourceManager.GetString("idling_behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idling complete, no more card drops available ähnelt.
        /// </summary>
        internal static string idling_complete {
            get {
                return ResourceManager.GetString("idling_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idling Order ähnelt.
        /// </summary>
        internal static string idling_order {
            get {
                return ResourceManager.GetString("idling_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idling paused ähnelt.
        /// </summary>
        internal static string idling_paused {
            get {
                return ResourceManager.GetString("idling_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore Steam client status ähnelt.
        /// </summary>
        internal static string ignore_client_status {
            get {
                return ResourceManager.GetString("ignore_client_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interface Language ähnelt.
        /// </summary>
        internal static string interface_language {
            get {
                return ResourceManager.GetString("interface_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading next game... ähnelt.
        /// </summary>
        internal static string loading_next {
            get {
                return ResourceManager.GetString("loading_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Idle Master Blacklist ähnelt.
        /// </summary>
        internal static string manage_blacklist {
            get {
                return ResourceManager.GetString("manage_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize Idle Master to system tray ähnelt.
        /// </summary>
        internal static string minimize_to_tray {
            get {
                return ResourceManager.GetString("minimize_to_tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next check ähnelt.
        /// </summary>
        internal static string next_check {
            get {
                return ResourceManager.GetString("next_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not in game ähnelt.
        /// </summary>
        internal static string not_ingame {
            get {
                return ResourceManager.GetString("not_ingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Official Github (Extended) ähnelt.
        /// </summary>
        internal static string official_github {
            get {
                return ResourceManager.GetString("official_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Official Group ähnelt.
        /// </summary>
        internal static string official_group {
            get {
                return ResourceManager.GetString("official_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default (Alphabetical Order) ähnelt.
        /// </summary>
        internal static string order_default {
            get {
                return ResourceManager.GetString("order_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prioritize games with the lowest number of available drops ähnelt.
        /// </summary>
        internal static string order_least {
            get {
                return ResourceManager.GetString("order_least", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prioritize games with the highest number of available drops ähnelt.
        /// </summary>
        internal static string order_most {
            get {
                return ResourceManager.GetString("order_most", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prioritize games with the highest card values ähnelt.
        /// </summary>
        internal static string order_value {
            get {
                return ResourceManager.GetString("order_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Pause Idling ähnelt.
        /// </summary>
        internal static string pause_idling {
            get {
                return ResourceManager.GetString("pause_idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please Login to Steam ähnelt.
        /// </summary>
        internal static string please_login {
            get {
                return ResourceManager.GetString("please_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please restart the application for language changes to take effect. ähnelt.
        /// </summary>
        internal static string please_restart {
            get {
                return ResourceManager.GetString("please_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die please wait... ähnelt.
        /// </summary>
        internal static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading badge page ähnelt.
        /// </summary>
        internal static string reading_badge_page {
            get {
                return ResourceManager.GetString("reading_badge_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Release Notes ähnelt.
        /// </summary>
        internal static string release_notes {
            get {
                return ResourceManager.GetString("release_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle Master Release Notes ähnelt.
        /// </summary>
        internal static string release_notes_title {
            get {
                return ResourceManager.GetString("release_notes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Resume Idling ähnelt.
        /// </summary>
        internal static string resume_idling {
            get {
                return ResourceManager.GetString("resume_idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save ähnelt.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle Master is saving your information ähnelt.
        /// </summary>
        internal static string saving_info {
            get {
                return ResourceManager.GetString("saving_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Settings ähnelt.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Steam username of signed on user ähnelt.
        /// </summary>
        internal static string show_username {
            get {
                return ResourceManager.GetString("show_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown when complete ähnelt.
        /// </summary>
        internal static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign In ähnelt.
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign Out ähnelt.
        /// </summary>
        internal static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signed in as ähnelt.
        /// </summary>
        internal static string signed_in_as {
            get {
                return ResourceManager.GetString("signed_in_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Skip Current Game ähnelt.
        /// </summary>
        internal static string skip_current_game {
            get {
                return ResourceManager.GetString("skip_current_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorting results based on your settings, please wait... ähnelt.
        /// </summary>
        internal static string sorting_results {
            get {
                return ResourceManager.GetString("sorting_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Statistics ähnelt.
        /// </summary>
        internal static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steam client status ignored ähnelt.
        /// </summary>
        internal static string steam_ignored {
            get {
                return ResourceManager.GetString("steam_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steam is not running ähnelt.
        /// </summary>
        internal static string steam_notrunning {
            get {
                return ResourceManager.GetString("steam_notrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steam is running ähnelt.
        /// </summary>
        internal static string steam_running {
            get {
                return ResourceManager.GetString("steam_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This Session ähnelt.
        /// </summary>
        internal static string this_session {
            get {
                return ResourceManager.GetString("this_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Update ähnelt.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update games status ähnelt.
        /// </summary>
        internal static string update_games_status {
            get {
                return ResourceManager.GetString("update_games_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data you&apos;ve entered isn&apos;t valid.  Please try again. ähnelt.
        /// </summary>
        internal static string validate_failed {
            get {
                return ResourceManager.GetString("validate_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validating... ähnelt.
        /// </summary>
        internal static string validating {
            get {
                return ResourceManager.GetString("validating", resourceCulture);
            }
        }
    }
}
